name: Manage TODOs

on:
  push:
  pull_request:

jobs:
  manage_todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run manageTodos script
        run: node manageTodos.js

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/todoDB.json docs/todos.md
          git diff --quiet && git diff --staged --quiet || git commit -m "chore(todos): Github action"
          git push
